import { StyleSheet } from "react-native";

export const commonStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#f5f6fa" },
  scrollContainer: { flexGrow: 1, padding: 20 },
  currentTime: {
    fontSize: 32,
    fontWeight: "bold",
    textAlign: "center",
    color: "#007AFF",
    marginBottom: 6,
  },
  gregorianDate: { fontSize: 18, textAlign: "center", color: "#333" },
  hijriDate: {
    fontSize: 16,
    textAlign: "center",
    color: "#555",
    marginBottom: 16,
  },
  title: {
    fontSize: 24,
    fontWeight: "700",
    textAlign: "center",
    color: "#333",
    marginVertical: 20,
  },
  dropdownWrapper: { marginBottom: 20, zIndex: 1000 },
  label: { fontSize: 16, marginBottom: 5, color: "#333" },
  card: {
    backgroundColor: "#fff",
    padding: 20,
    marginVertical: 8,
    borderRadius: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 3,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  prayerName: { fontSize: 16, fontWeight: "500", color: "#333" },
  prayerTime: { fontSize: 16, fontWeight: "600", color: "#007AFF" },
  loading: {
    fontSize: 16,
    textAlign: "center",
    color: "#888",
    marginVertical: 30,
  },
  buttonCard: {
    backgroundColor: "#FF6B6B",
    paddingVertical: 16,
    borderRadius: 14,
    alignItems: "center",
    marginTop: 20,
    elevation: 3,
  },
  buttonText: { color: "#fff", fontWeight: "600", fontSize: 16 },
});
